### PR TITLE
The check command should time out

### PR DESCRIPTION
**Pull request by CSilivestru**
- [x] Timeout after 5 minutes
- [x] Minor improvement on the 404 response since it could just mean the sha is no longer in the tree
- [x] Make it configurable

Goes with https://github.com/bithound/app.bithound.io/pull/2664

### CODE REVIEW

**Comment by gtanner** [comment]
Lets add a `--timeout` option to the options as well, might as well make it configurable.

**Comment by CSilivestru** [comment]
Good idea :-)

**Comment by gtanner** [comment]
nitpick: Why is the default 10 minutes but we only accept configuration values in seconds?

Wouldn't it make more sense to only accept configuration in minutes?

Do we need sub 1 minute granularity in the timeout?

**Comment by CSilivestru** [comment]
YOU KNOW WHAT?!

You're right. I'll change it :-P

**Comment by CSilivestru** [comment]
We'll do minutes because a sub one-minute timeout is kinda dumb when you think about it

**Comment by gtanner** [comment]
+R

**Pull request merged**
