### PR TITLE
Adding appveyor support

### PR DESCRIPTION
**Pull request by jfugett**
Adding default support for appveyor so environment variables don't have to be exported to force support.

### CODE REVIEW

**Comment by gtanner** [comment]
Looks cool!

Can you remove the `.idea/watcherTasks.xml` file?

**Comment by jfugett** [comment]
will do, might be later tonight before I can get to it

**Comment by jfugett** [comment]
@gtanner Updated let me know if you would like me to rebase/squash or if any of the unit tests aren't working on your end. Got a failure running them from the fork as it expected a specific url.

**Comment by gtanner** [comment]
I am not that much of a perfectionist to force you to squash the commits :)

I see why the tests are failing, I will clean those up before I publish to NPM

**Pull request merged**
