### PR TITLE
process.env.TRAVIS_BRANCH fix

### PR DESCRIPTION
**Pull request by vrtxf**
TRAVIS_BRANCH:For builds not triggered by a pull request this is the name of the branch currently being built; whereas for builds triggered by a pull request this is the name of the branch targeted by the pull request (in many cases this will be master).

### CODE REVIEW

**Comment by vrtxf** [comment]
On a 2nd note program.branch doesn't default to anything for me so it's likely the branch needs to be determined inside the loop. Will just running the exec command on $(git branch | sed -n -e 's/^\* \(.*\)/\1/p') do the trick here?

I see different opinions on how to fetch the current branch via cli and NodeGit package but they both exceed the scope of a default case. For now the only thing this PR fixes is the error message, from "Repo or commit not found" ("master" branch name inside PR and proper SHA) to "Branch could not be determined" (undefined branch name and proper SHA).

The proper branch still needs to be determined for travis and the best way I think is to open TRAVIS_BUILD_DIR with NodeGit and get the branch once a TRAVIS_PULL_REQUEST is not false. What are your thoughts on this ?

**Comment by vrtxf** [comment]
Hi this is still an issue visible here: [travis:superleap/github-issues-label-sync^gils19-semantic-release-fix](https://travis-ci.org/superleap/github-issues-label-sync/jobs/145139759)
Bithound fails under a pull request branch because the origin is unknown and branch resolves to target. Only effective way around this is to currently disable bithound checks on travis pull request variable existence which goes against the documentation. 
I am keen to put in a fix for branch determination once you decide the best way to go at it !

**Comment by vrtxf** [comment]
Hi I updated the fix with getting the correct branch. I will add a travis test and paste the result here if it works

**Comment by dansilivestru** [comment]
+R and thank you :-)

**Pull request merged**
